### ISSUE TITLE
ewtsconverter dependency

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lucene-bo#1]
The dependency on ewts-converter 1.2.0 seems to be missing a jar at search.maven.org.

Temporarily added ewts-converter-1.2.0.jar to buda-base to move forward on testing

**Comment by eroux** [comment]
Indeed, that's intended because the dependencies are supposed to be managed by maven... If we want to have a jar that include all dependencies, I'll write some options in the building process and we can release it on the github page

**Comment by xristy** [comment]
That would be great! I assume there's a way to indicate in the pom that the ewts-converter jar should be included somehow in the target jar and then that single jar would be a self-contained analyzer for use in Lucene. 

I can think of several use cases for lucene-bo that would not involve maven such as adding lucene-bo to fuseki.
